configure:
	frizzante configure

test:
	frizzante test

build:
	frizzante build

dev:
	frizzante dev

check:
	frizzante check

clean:
	frizzante clean

format:
	frizzante format

install:
	frizzante install

update:
	frizzante update

migrate:
	frizzante migrate

.PHONY: migrate
.PHONY: configure
.PHONY: test
.PHONY: build
.PHONY: dev
.PHONY: check
.PHONY: clean
.PHONY: format
.PHONY: install
.PHONY: update