name: build
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fix:
    name: fix
    runs-on: ubuntu-latest
    steps:
      - name: fix go.mod
        id: fix_go_mod
        run: .github/scripts/100.fix_go_mod.sh
  tests:
    needs:
      - fix
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run tests
        id: run_tests
        run: .github/scripts/200.run_tests.sh
  publish:
    needs:
      - tests
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: create identity
        id: create_identity
        run: .github/scripts/300.create_identity.sh
      - name: create tag
        id: create_tag
        run: .github/scripts/400.create_tag.sh
      - name: save changes
        id: save_changes
        run: .github/scripts/500.save_changes.sh