name: Publish
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        id: publish
        run: .github/scripts/publish.sh