name: Publish
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: run_tests
        run: .github/scripts/100.run_tests.sh
  publish:
    needs:
      - tests
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Fix Version
        id: fix_version
        run: .github/scripts/200.fix_version.sh
      - name: Create identity
        id: create_identity
        run: .github/scripts/300.create_identity.sh
      - name: Create zip
        id: create_zip
        run: .github/scripts/400.create_zip.sh
      - name: Create tag
        id: create_tag
        run: .github/scripts/500.create_tag.sh
      - name: Save changes
        id: save_changes
        run: .github/scripts/600.save_changes.sh