name: tests
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        id: prepare
        run: .github/scripts/prepare.sh
      - name: test
        id: test
        run: .github/scripts/test.sh