name: tests
on:
  - workflow_dispatch
  - push
permissions:
  contents: write
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: tests
        id: tests
        run: |
          ./scripts/clean.sh
          ./scripts/initialize.sh
          ./scripts/package.sh
          ./scripts/test.sh