name: tests
on:
  - pull_request
  - push
  - workflow_dispatch
permissions:
  contents: write
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tests
        id: tests
        run: make test